### model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
# 如果要做增量训练，可取消注释并改成已有 LoRA adapter 目录。
# adapter_name_or_path: saves/serial_suites/requested_suite/lr_0.0001_bs_16_seed_42/agriculture_5k/clean_model/adapter

### method
stage: ttl
do_train: true
do_predict: true
finetuning_type: lora
lora_target: q_proj,v_proj
trust_remote_code: true

### ttl parameters
setting: offline_ttl
threshold: 3
lamb: 0.1

### dataset
dataset: agriculture_5k
eval_dataset: agriculture_5k
dataset_dir: data
template: qwen
cutoff_len: 4096
max_samples: 41000
overwrite_cache: true
preprocessing_num_workers: 8

### output
# 串行模板脚本会按每轮自动覆盖 dataset、eval_dataset 和 output_dir。
output_dir: saves/yaml_runs/offline_ttl/agriculture_5k/lamb_0.1-threshold_3-lr_5e-5-seed_42

logging_steps: 10
save_steps: 8000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1 
learning_rate: 5.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
seed: 42
bf16: true
ddp_timeout: 180000000

### eval
do_eval: null

### predict
temperature: 0.0
do_sample: false
max_new_tokens: 512
per_device_eval_batch_size: 1
predict_with_generate: true

report_to: none
