### model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
adapter_name_or_path: ../do_as_I_do/saves/train/gsm8k_AOA/bs_16_lr_0.0001_seed_42

### method
stage: ttl
setting: offline_ttl
do_train: true
do_predict: false
predict_with_generate: false
finetuning_type: lora
lora_target: q_proj,v_proj
trust_remote_code: true

### ttl parameters
threshold: 3
lamb: 0.1

### optional swanlab
use_swanlab: true
swanlab_project: do_as_i_do
swanlab_experiment_name: gsm8k_vallina_AOA_train
swanlab_workspace: qding666
swanlab_mode: cloud

### dataset
dataset: vallina_harmful_AOA
eval_dataset: vallina_harmful_AOA
dataset_dir: ../do_as_I_do/data
template: qwen
cutoff_len: 1536
max_samples: 41000
overwrite_cache: true
preprocessing_num_workers: 8

### output
output_dir: ../do_as_I_do/saves/train/gsm8k_vallina_AOA/bs_16_lr_0.0001_seed_42
logging_steps: 10
save_steps: 8000
plot_loss: true
overwrite_output_dir: true
report_to: none

### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
seed: 42
bf16: true
ddp_timeout: 180000000

### eval
do_eval: false

### predict
temperature: 0.0
do_sample: false
max_new_tokens: 256
per_device_eval_batch_size: 16
